# -*- coding: utf-8 -*-
"""Task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nf6Q9IHH5kBeKGe1BFRai4UuBIfnaIV6
"""

import sqlite3
import pandas as pd

# Load your CSV
df = pd.read_csv("/content/olist_order_items_dataset.csv")

# Create and connect to SQLite database
conn = sqlite3.connect("sales_data.db")

# Save DataFrame as a table in SQLite
df.to_sql("sales", conn, if_exists="replace", index=False)

query = """
SELECT
    product_id,
    COUNT(*) AS total_items_sold,
    SUM(price) AS total_revenue
FROM sales
GROUP BY product_id
ORDER BY total_revenue DESC
"""
result_df = pd.read_sql_query(query, conn)
print(result_df.head())

import matplotlib.pyplot as plt

# Let's show top 10 products by revenue
top_10 = result_df.head(10)

top_10.plot(kind="bar", x="product_id", y="total_revenue", legend=False)
plt.title("Top 10 Products by Revenue")
plt.xlabel("Product ID")
plt.ylabel("Revenue")
plt.tight_layout()
plt.savefig("top_products_revenue.png")  # optional
plt.show()